# A stream that listens on UDP port 5244 for HTTP logs from HAproxy after request response completes.

CREATE STREAM http_log_on_request_completion (
        schema	        	string,
        event_stage		string,
        traffic_mode		string,
        request_id		string,
        accept_ts_ms		number,
        request_ts_ms		number,
        source_ip		string,
        source_port		number,
        real_client_ip		string,
        frontend_ip		string,
        frontend_port		number,
        frontend_name		string,
        tls	        	string,
        sni     		string,
        tls_protocol		string,
        tls_cipher		string,
        alpn    		string,
        host	        	string,
        method	        	string,
        path	        	string,
        query_string		string,
        full_url		string,
        http_version		string,
        user_agent		string,
        referer	        	string,
        user_header		string,
        client_key		string,
        tenant_id		string,
        session_id		string,
        login_identifier	string,
        mcp_client_id		string,
        mcp_session_id		string,
        mcp_tool_name		string,
        active_conn		number,
        frontend_conn		number,
        policy_action		string,
        policy_param		string,
        endpoint_rate_limit	number,
        endpoint_rate_current	number,
        status_code		number,
        backend_name		string,
        server_name		string,
        server_ip		string,
        server_port		string,
        bytes_uploaded		number,
        bytes_sent		number,
        request_header_time_ms	number,
        queue_time_ms		number,
        connect_time_ms		number,
        response_header_time_ms	number,
        response_data_time_ms	number,
        total_time_ms		number,
        active_time_ms		number,
        termination_state	string,
        backend_conn		number,
        server_conn		number,
        backend_queue		number,
        server_queue		number,
        cache_status		string,
        x_cache	                string,
        response_content_length	string
)
INPUT UDP(port 5244)
PARSER log(
        pattern '* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
'
);
